In [1]:
import pandas as pd

In [2]:
amazon = pd.read_csv(r'../Datasets/amazon_prime_titles.csv', encoding = 'utf-8')
amazon.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [3]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7586 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [4]:
amazon.isnull().sum()

show_id            0
type               0
title              0
director        2082
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [5]:
amazon.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1266,s1267,TV Show,Presunto Culpable,NaN,"Miguel angel Muñoz, Susi Sanchez, Elvira Mingu...",NaN,NaN,2018,NR,1 Season,"Drama, Suspense","Jon, un investigador que vuelve a su pueblo de..."
1975,s1976,TV Show,Kabaneri of the Iron Fortress (Original Japane...,NaN,NaN,NaN,NaN,2016,TV-MA,1 Season,Anime,"The world is overrun with Kabane, zombie-like ..."
974,s975,Movie,Sleepytime Gorilla Museum,Baeble Music,NaN,NaN,NaN,2011,NR,55 min,Comedy,Experimental rockers Sleepytime Gorilla Museum...
8180,s8181,Movie,The Cutter,William Tannen,"Chuck Norris, Joanna Pacula, Marshall Teague, ...",NaN,NaN,2006,R,91 min,Action,In the aftermath of a daring rescue mission go...
590,s591,TV Show,The Kennedys,NaN,"Katherine Parkinson, Dan Skinner, Lucy Hutchinson",NaN,NaN,2015,TV-14,1 Season,Comedy,"It's 1978, and Brenda, Tony and Emma Kennedy m..."

In [6]:
disney=pd.read_csv(r'../Datasets/disney_plus_titles.csv', encoding = 'utf-8')
disney.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

In [7]:
hulu=pd.read_csv(r'../Datasets/hulu_titles.csv', encoding = 'utf-8')
hulu.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...

In [8]:
netflix=pd.read_csv(r'../Datasets/amazon_prime_titles.csv', encoding = 'utf-8')
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [9]:
amazon_df=amazon.copy()
disney_df=disney.copy()
hulu_df=hulu.copy()
netflix_df=netflix.copy()

In [10]:
amazon_df['Plataforma']='amazon'
disney_df['Plataforma']='disney'
hulu_df['Plataforma']='hulu'
netflix_df['Plataforma']='netflix'

In [11]:
hulu_df['duration'].fillna('sin datos',inplace=True)
netflix_df['duration'].fillna('sin datos',inplace=True)

In [12]:
def sepdurationcolum(df):
    df['temporadas']=df['duration'].apply( lambda i: i.split()[0] if i.split()[1]=='Season' else '0')
    df['duracion_peliculas']=df['duration'].apply( lambda i: i.split()[0] if i.split(" ",1)[1]=='min' or i.split(" ",1)[1]=='min' else '0')
    return df

In [13]:
amazon_df=sepdurationcolum(amazon_df)
disney_df=sepdurationcolum(disney_df)
hulu_df=sepdurationcolum(hulu_df)
netflix_df=sepdurationcolum(netflix_df)

In [14]:
amazon_df.drop(columns='duration', inplace=True)
disney_df.drop(columns='duration', inplace=True)
hulu_df.drop(columns='duration', inplace=True)
netflix_df.drop(columns='duration', inplace=True)

In [15]:
final_df=pd.concat([amazon_df, disney_df, hulu_df, netflix_df], axis=0)

In [16]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23859 entries, 0 to 9667
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   show_id             23859 non-null  object
 1   type                23859 non-null  object
 2   title               23859 non-null  object
 3   director            16152 non-null  object
 4   cast                18130 non-null  object
 5   country             4195 non-null   object
 6   date_added          4802 non-null   object
 7   release_year        23859 non-null  int64
 8   rating              22662 non-null  object
 9   listed_in           23859 non-null  object
 10  description         23855 non-null  object
 11  Plataforma          23859 non-null  object
 12  temporadas          23859 non-null  object
 13  duracion_peliculas  23859 non-null  object
dtypes: int64(1), object(13)
memory usage: 2.7+ MB

SEGUNDA CONSULTA

In [17]:
((final_df['Plataforma']=='netflix') & (final_df['type'].str.contains('Movie'))).sum()

7814

In [18]:
((final_df['Plataforma']=='netflix') & (final_df['type'].str.contains('TV Show'))).sum()

1854

TERCERA CONSULTA

In [19]:
((final_df['listed_in'].str.contains('Comedy')) & (final_df['Plataforma']=='amazon')).sum()

2099

CUARTA CONSULTA

In [20]:
final_df.sample(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Plataforma,temporadas,duracion_peliculas
1039,s1040,Movie,Shakuntala Devi,Anu Menon,"Vidya Balan, Sanya Malhotra, Jisshu Sengupta, ...",India,NaN,2020,13+,Drama,"The extraordinary story of Shakuntala Devi, th...",amazon,0,127
4417,s4418,Movie,Dumb-ish,Azim Lateef,"Jennifer Hardwick, Mehgan James, Kendra LaChon...",NaN,NaN,2015,18+,Comedy,DUMB-ISH is an urban classic tale about 2 room...,netflix,0,68
4016,s4017,Movie,JFK's Women: The Scandals Revealed,Harvey Lilley,"Andrew Cook, Piers Gibbon, Donald Rumbelow",NaN,NaN,2006,13+,"Special Interest, Suspense",John F. Kennedy was arguably the most charisma...,netflix,0,52
5689,s5690,Movie,Omerta: The Act Of Silence,Craig Syracusa,NaN,NaN,NaN,2021,18+,Suspense,At a time when political power and legal juris...,amazon,0,85
8937,s8938,Movie,3 Pints and a Rabbi,Richard J. Perry,"Amanda Abbington, Michael Maloney, Jordan Step...",NaN,NaN,2021,18+,"Comedy, Science Fiction",When three dazed and confused strangers wake u...,amazon,0,73
643,s644,TV Show,The Kings,NaN,NaN,NaN,"June 6, 2021",2021,NaN,"Documentaries, Sports",A four-part series showcasing four champions w...,hulu,1,0
263,s264,TV Show,Secrets Of The Zoo,NaN,Mocean Melvin,NaN,"April 2, 2021",2017,TV-PG,"Animals & Nature, Docuseries, Family",Go behind the scenes at The Columbus Zoo and A...,disney,0,0
2877,s2878,TV Show,Chasing The Crown: Dreamers to Streamers,NaN,"Tucker Boner aka Jericho, AnneMunition, Action...",NaN,NaN,2020,13+,Adventure,Three Twitch streamers have their sights set o...,amazon,1,0
3486,s3487,Movie,2ELEVEN,Derek Scott,"Murda Pain, Chamar Avery, Martell Lane",NaN,NaN,2017,18+,"Action, Drama",Ucult Studios presents a tale of the two broth...,netflix,0,108
4474,s4475,Movie,Wetbacks,Hank McCune,"Lloyd Bridges, Nancy Gates, Barton MacLane, Jo...",NaN,NaN,1956,18+,Drama,Former Coastguardsmen Jim Benson is about to l...,netflix,0,87
2980,s2981,TV Show,Upstairs Downstairs,NaN,NaN,United Kingdom,"September 24, 2013",2011,TV-14,"Drama, International",Revival of the iconic '70s series set in a Lon...,hulu,0,0
5532,s5533,Movie,RiffTrax Live: Time Chasers,Michael J. Nelson,"Michael J. Nelson, Kevin Murphy, Bill Corbett,...",NaN,NaN,2016,16+,"Comedy, Science Fiction","Time Chasers, the story of a man named Nick wh...",amazon,0,106
7151,s7152,Movie,Stag Hunt,James Shanks,"Mackenzie Astin, Neil Cole",NaN,NaN,2014,13+,"Action, Adventure",Badly planned trek across Dartmoor landscape b...,amazon,0,93
8044,s8045,Movie,Concrete Plans,William Jewell,"Amber Rose Revah, Charley Palmer Rothwell, Chr...",NaN,NaN,2021,18+,"Horror, Suspense",When their employer tries to cheat them out of...,netflix,0,91
4513,s4514,Movie,Interlude,Herve Bodilis,"Vincent Winterhalter, Sopnie Verbeek, Dinara D...",NaN,NaN,2016,R,"Comedy, International",Raphaël buys a boat and convinces his two frie...,amazon,0,95
3661,s3662,Movie,Thomas & Friends: Big World! Big Adventures! -...,David Stoten,NaN,NaN,NaN,2018,NaN,"Animation, Kids",Thomas is inspired to embark on an ambitious t...,amazon,0,82
5546,s5547,TV Show,4 Cars,NaN,Gren Brooke,NaN,NaN,2016,ALL,"Animation, Kids","4 colored cars: red, yellow, green and blue. E...",amazon,1,0
467,s468,Movie,Diary of a Wimpy Kid: The Long Haul,David Bowers,"Jason Drucker, Alicia Silverstone, Tom Scott, ...",United States,"July 17, 2020",2017,PG,"Comedy, Family",A trip to Meemaw’s 90th birthday takes a detou...,disney,0,92
8518,s8519,Movie,Butter (1998) (aka Never 2 Big),Peter Gathings Bunche,"Ernie Hudson, Nia Long, Tony Todd, Donnie Wahl...",NaN,NaN,1998,R,"Action, Arts, Entertainment, and Culture, Susp...","Deceit, body heat and pulsing street beats con...",amazon,0,101
7365,s7366,Movie,Apex Predators,Dustin Ferguson,NaN,NaN,NaN,2021,16+,Action,When the bodies of beach-goers begin washing a...,netflix,0,70